tests/bench_compare.sh, tests/test_advanced.py, tests/test_benchmark.py
=> Add travis perf test shell

Changelog.rst, py7zr/compression.py
=> Use seek and truncate for padding

py7zr/archiveinfo.py, py7zr/py7zr.py, tests/test_basic_unit.py, tests/test_compress.py
Add logics and test for encoded header.
=> Support writing encoded header

README.rst
=> maybe typo

docs/7zFormat.rst, py7zr/py7zr.py, setup.cfg, tests/test_archive.py, tests/test_extract.py
- Fix to create proper symlink entry. (fixes #43)
- Add test for symlinks.
- Fix a document about format related to CRC.
=> Fix and support symlink archive (fixes #43)

.travis.yml, appveyor.yml, azure-pipelines.yml, py7zr/compression.py, tests/test_extract.py, tests/test_unit.py, tox.ini
=> Replace concurrent with multiprocessing module

Changelog.rst, py7zr/cli.py, tests/test_basic.py
=> CLI: Ask password with getpass standard library

py7zr/archiveinfo.py, py7zr/properties.py
=> Introduce some functions for multivolume archive

tox.ini
https://tox.readthedocs.io/en/latest/config.html#conf-ignore_errors
=> Ignore errors in check env so all are shown

requirements.txt, setup.cfg
=> Make pywin32 a regular runtime dependency

tests/test_benchmark.py
=> Add decrypt benchmark

py7zr/py7zr.py, tests/test_archive.py, tests/test_basic.py
=> Fix solid detection and test case

py7zr/extra.py, py7zr/helpers.py
=> Introduce zero-copy Buffer helper

py7zr/helpers.py, tests/test_unit.py
=> Add new calculate_key helper function

.travis.yml, py7zr/helpers.py, tests/test_unit.py
=> Travis: test with pypy3.6-7.2.0 on bionic

py7zr/helpers.py, tests/test_unit.py
pypy3 has a cffi interface for hashlib
=> helper: use _hashlib.new() for key calculation

py7zr/compression.py, py7zr/helpers.py, py7zr/py7zr.py, tests/test_archive.py, tests/test_unit.py
=> Better handing of f.origin path object

tox.ini
=> tox: add --quiet for isort check

py7zr/py7zr.py, tests/test_basic.py
=> provide FileInfo object property crc

docs/filters.rst, docs/index.rst
=> docs: Add fitter examples

py7zr/cli.py, py7zr/compressor.py, py7zr/helpers.py, py7zr/properties.py, py7zr/py7zr.py, tests/test_basic.py, tests/test_extra_codecs.py, tests/test_info.py, tests/test_unit.py
=> Update archiveinfo() to support additional methods

py7zr/compressor.py
Move most predicted logic to a top of functions and add pragma for coverage.
Update alignment calculation for better performance.
=> Refactoring AESCompressor/Decompressor

py7zr/py7zr.py
=> Refactoring SevenZipFile class

py7zr/compressor.py, tests/test_extra_codecs.py
=> Handle password at SevenZip(De)Compressor

py7zr/compressor.py, tests/test_unit.py
=> Use SupportedMethods.is_crypto_id() to detemin method requires password

py7zr/archiveinfo.py, py7zr/py7zr.py, tests/test_archive.py
- Add test for compabitility check
- Fix header compression logic
=> Support encoded headers

docs/archive_format.rst
=> spec: change CRC algorithm as normative

Changelog.rst, docs/archive_format.rst
=> docs: update specs

py7zr/archiveinfo.py, py7zr/py7zr.py, tests/test_basic.py
Implement Header.size calculation
=> Fix header.size calculation

py7zr/archiveinfo.py
=> Drop additional_streaminfo handler

.readthedocs.yml, docs/conf.py, docs/contribution.rst
=> docs: Add rtd.org config

docs/archive_format.rst, docs/conf.py, setup.cfg
Update specification using a4doc, presenting railroad diagram
=> docs: Update specification with sphinx-a4doc

README.rst
=> README: add links for documents

py7zr/cli.py
=> CLI: catch exception during decompression

py7zr/cli.py
=> Backport: CLI: catch exception during decompression

docs/archive_format.rst, py7zr/archiveinfo.py, tests/test_unit.py
=> Update SubStreamsInfo writing sizes

py7zr/archiveinfo.py, py7zr/compressor.py, py7zr/py7zr.py, tests/test_archive.py, tests/test_extract.py, tests/test_unit.py
=> Fix PackInfo digest read/write logic

py7zr/archiveinfo.py, py7zr/compressor.py, py7zr/py7zr.py, tests/test_archive.py, tests/test_extract.py, tests/test_unit.py
=> Topic backport packinfo digest

docs/archive_format.rst
=> docs: spec: update attributes field description

docs/archive_format.rst
Specification work-in-progress
=> docs: spec: Update descriptions

docs/archive_format.rst
=> docs: spec: fix substreaminfo

py7zr/compressor.py, py7zr/py7zr.py
Current buffer handling in DecompressorChain is not optimal.
This improve a way to handle input of decompression data.
=> Improve decompress performance

py7zr/compressor.py
=> Improve DecompressChain logics

py7zr/compressor.py
=> Each decompressor accept max_length

py7zr/archiveinfo.py, py7zr/compressor.py, py7zr/py7zr.py, tests/test_extra_codecs.py, tests/test_unit.py
Newer compressor such as ZStandard has an API that handle file object directly.
This refactoring to move a file read/write loop into SevenZipCompressor/Decompressor class from Worker class.
It is a preparation for supporting ZStandard in py7zr.
=> Handle file read/write in SevenZipCompressor/Decompressor class

py7zr/__init__.py, py7zr/cli.py, py7zr/compressor.py, py7zr/exceptions.py, tests/test_encryption.py
=> Backport: Raise PasswordRequired when no password is given for encrypted archive

Changelog.rst, docs/archive_format.rst, py7zr/archiveinfo.py, py7zr/helpers.py, py7zr/py7zr.py, tests/test_archive.py, tests/test_basic.py, tests/test_unit.py
=> Support append 'a' mode

README.rst, docs/user_guide.rst, py7zr/cli.py, tests/test_archive.py, tests/test_basic.py
Add append mode for CLI command
=> CLI: append mode

py7zr/cli.py, tests/test_basic.py
=> CLI: Catch LZMAError when wrong password is given

py7zr/cli.py, tests/test_basic.py
CLI: catch exception when corrupted data and password wrong.
=> Backport: cli catch exception corrupted data(#229)

py7zr/py7zr.py
=> Skip extraction of folder when no target exist in the folder

docs/api.rst
=> docs: update api document about read(), readall() and exract(targets=)

py7zr/archiveinfo.py
=> Avoid re-read header to calculate crc32

py7zr/archiveinfo.py
=> Backport: Avoid re-read header to calculate crc32

.github/workflows/run-tox-tests.yml, setup.cfg, tests/__init__.py, tests/test_archive.py, tox.ini
=> compatibility test with libarchive

py7zr/archiveinfo.py
=> Fix reading header which is larger than buffer size(#252)

.github/workflows/run-tox-tests.yml, tests/test_archive.py, tests/test_extract.py
=> GHA: Change set-env to new syntax

.github/workflows/publish-to-test-pypi.yml, .github/workflows/run-tox-tests.yml, py7zr/cli.py, tests/test_basic.py, tox.ini
=> GHA: ci test with py39

.travis.yml, py7zr/win32compat.py, tox.ini
=> Travis: build and test on arm64

Changelog.rst, py7zr/compressor.py, py7zr/helpers.py
Use PpmdEncoder/PpmdDecoder instead of Bufferd one.
=> Patch update ppmd

py7zr/compressor.py
=> ppmd: delayed initilize decompressor

py7zr/compressor.py, setup.cfg
=> Bump to ppmd-cffi@v0.3.1

py7zr/py7zr.py
Fixed issue #275 of original repository. For more details read here:
https://github.com/miurahr/py7zr/issues/275
=> Fixed issue #275 of original repository

py7zr/py7zr.py, tests/test_encryption.py
=> Fix writing header encryption mode

.github/workflows/run-tox-tests.yml
=> GHA: update coveralls scripts

py7zr/compressor.py, setup.cfg, tox.ini
=> Escalate ppmd/zstandard as default dependency modules

py7zr/bcjfilter.py, py7zr/compressor.py
also avoid multiple inheritance
=> Refactoring BCJFilter move to another module

.github/workflows/run-benchmark.yml, .github/workflows/run-tox-tests.yml, azure-pipelines.yml, tests/conftest.py, tests/test_benchmark.py, tox.ini
- Add extra_info to output.json
- ratio and rate
- pytest options will be given by CI configuration
=> CI: update benchmark

py7zr/compressor.py, setup.cfg
Utilize BCJ filter implemented in C with CFFI for performance/speed.
=> Use BCJ filter with CFFI interface

py7zr/py7zr.py, tests/test_misc.py
=> Introduce writed(dict) method

py7zr/cli.py, py7zr/compressor.py, tests/test_basic.py
=> CLI: Fix getting module_name

py7zr/cli.py, py7zr/compressor.py, py7zr/helpers.py, py7zr/properties.py, py7zr/py7zr.py
=> READ_BLOCKSIZE configurable

docs/api.rst, py7zr/compressor.py, py7zr/pyzstdfilter.py, py7zr/zstdfilter.py, setup.cfg, tests/test_benchmark.py, tests/test_extra_codecs.py, tox.ini
Prefers to use pyzstd on CPython and use python-zstandard on PyPy.
=> utilize pyzstd

py7zr/py7zr.py, tests/test_archive.py, tests/test_encryption.py
=> Compress empty file as a zero sized stream, instead of emptystream(#305)

setup.cfg
=> Bump BCJ @0.5.1 and PPMd @0.4.1

tests/test_benchmark.py
=> test: benchmark: add ppmd text test

tests/test_extra_codecs.py
=> Drop zstd unit test for compression

py7zr/py7zr.py, tests/test_extract.py
=> Don't produce directory when memory extract mode

py7zr/cli.py
=> CLI: add -P --password option for create subcommand

.github/workflows/run-tox-tests.yml
=> CI: test on aarch64 Ubuntu

README.rst
=> added conda recipe #342

.github/workflows/codeql-analysis.yml
=> Add codeQL job

docs/api.rst
=> docs: add description of ArchiveInfo class

pyproject.toml, setup.cfg, tox.ini
=> remove tool configuration from tox.ini

docs/api.rst, py7zr/cli.py, py7zr/compressor.py, py7zr/py7zr.py, tests/test_info.py
=> Improve ArchiveInfo.method_names as list[str]

setup.cfg
=> Allow pyzstd@0.15.0

.github/workflows/run-tox-tests.yml
=> CI: test on python3.10.0

pyproject.toml
=> test: add tox target mprof for memory profiling

py7zr/properties.py
=> Reduce default buffer size not in 64bit platforms

py7zr/compressor.py
=> Decompressor read data only when unused data is not enough

py7zr/archiveinfo.py
=> read_utf16: decode after reading the entire string

py7zr/compressor.py
=> Fix UnsupportedCompresssionMethodError arguments

py7zr/compressor.py, tests/test_encryption.py
- Handle the case when LZMA2+BCJ+7zAES
- resolve #392
=> Allow compression/encryption with 7zAES +LZMA2+BCJ

py7zr/helpers.py, py7zr/py7zr.py
=> Fix mypy type check errors

py7zr/py7zr.py
- The fix proposed in issue #406
- Thanks @h-j-13
=> Check traversal attack file path

docs/archive_format.rst
=> docs: Add several known method ID to the specification

py7zr/compressor.py
=> Update error message for unsupported methods

.github/workflows/run-tox-tests.yml
=> Actions: bump libarchive@3.5.3 for windows

py7zr/py7zr.py
=> mypy: ignore stat attributes

py7zr/py7zr.py, setup.cfg
=> Work around for mypy errors

README.rst, tests/test_basic.py
- Update README to fix syntax error
- Change test to use same syntax with README
resolve #425
=> Fix targets argument example in README and test

py7zr/compressor.py, setup.cfg
=> Bump pyppmd@0.18.1

.github/workflows/run-tox-tests.yml
=> Actions: fix test dependency installation

.github/workflows/run-tox-tests.yml, azure-pipelines.yml, pyproject.toml, setup.cfg, setup.py
=> pyproject.toml: fix setuptools_scm configuration

py7zr/properties.py
- change default_limit to 128MB
=> Change chunk size limit

py7zr/cli.py
- file creation code is duplicated
- resolve #442
=> Cli/create: fix duplicated code

py7zr/archiveinfo.py, py7zr/py7zr.py, tests/test_archive.py
=> Fix a case to produce broken archive when appending empty

docs/contribution.rst
- Add explanation of profiling
=> docs: update developer guide

.github/workflows/codeql-analysis.yml
- Avoid duplicated run on pull_request
- Update codeql
- Remove periodical run for codeql
=> Actions: update trigger condition

.github/workflows/run-tox-tests.yml, azure-pipelines.yml
and update setuptools before running tox
=> actions: specify  a checkout fetch depth for all patterns

tests/test_archive.py
=> tests: enable skipped cases for zstandard

.github/workflows/publish-to-pypi.yml
- use 'python -m build' for building wheel
- update action trigger
=> actions: fix publish script

.github/workflows/run-tox-tests.yml, .readthedocs.yml, README.rst, pyproject.toml, setup.cfg
=> bump setuptools@63 and setuptools_scm@7

README.rst, py7zr/compressor.py, py7zr/py7zr.py, pyproject.toml, setup.cfg, tests/test_extra_codecs.py
=> Support enhanced deflate compression

tests/test_attack.py
=> Add test against symlink attack

README.rst
=> fix documentation

py7zr/helpers.py
=> Use hashlib instead of _hashlib

.github/workflows/run-benchmark.yml, .github/workflows/run-tox-tests.yml, pyproject.toml
- Change target python to 3.11 and pypy-3.9
- Bump actions/checkout@v3 and actions/setup-python@v4
- Run on ubuntu-22.04
=> Actions: update scripts

py7zr/py7zr.py
=> Drop manual GC call on close()

README.rst
Add security notification about CVE-2022-44900 and appreciation to Matteo.
=> README: add security notifiation

README.rst
=> fix typo in the readme my_filter to my_filters

py7zr/helpers.py, tests/test_extract.py
https://github.com/miurahr/aqtinstall/issues/701
=> fix: allow specify target path in relative path

py7zr/exceptions.py, py7zr/py7zr.py, tests/test_archive.py
- default arcname from sanitized target path
- write sanitize path
- add test
- resolve #525
=> fix: sanitize target path when write - handle absolute paths

py7zr/archiveinfo.py, py7zr/cli.py, py7zr/compressor.py, py7zr/py7zr.py, pyproject.toml
- mypy: Enable check for untyped defs
=> refactor: improve type safe

README.rst, docs/CODE_OF_CONDUCT.rst, docs/index.rst
- Add CODE_OF_CONDUCT.rst
- Update README.rst and index.rst to refer
=> docs: Addition of code of conduct

.github/ISSUE_TEMPLATE/pull_request_template.md
Add template for PR
It will lead better PR description.
-  work flow improvement
- N.A.
- Add template file
=> chore: Create pull_request_template.md

docs/user_guide.rst
- issue #557
- It set an explanation to create multi-volume archive as an individual sub-section
=> docs: make subsection of multivolume creation

py7zr/properties.py
- Other
- issue #??
- function is_64bit() in properties.py
n/a
=> fix bug in function is_64bit()

pyproject.toml
- N/A
Clean up after https://github.com/miurahr/py7zr/pull/552
=> Remove pyannotate from pyproject.toml

py7zr/py7zr.py, tests/test_basic.py
- https://github.com/miurahr/py7zr/issues/587
- Add support for `mode="x"` in `py7zr.SevenZipFile()`
N/A
=> feat: add support for `mode="x"` in `py7zr.SevenZipFile()`

README.rst, pyproject.toml
- issue #594
- Minimum required python version is 3.8
-
-
=> chore: minimum requirement to python 3.8

docs/api.rst
- https://github.com/miurahr/py7zr/pull/609
- https://github.com/miurahr/py7zr/issues/608
Add documentation for `SevenZipFile.getinfo()`
=> docs: add getinfo()

docs/Changelog.rst, docs/archive_format.rst, docs/contribution.rst, docs/previous_changes.rst, py7zr/archiveinfo.py, py7zr/cli.py, py7zr/compressor.py, py7zr/py7zr.py, tests/test_cli.py, tests/test_misc.py, tests/test_unit.py
- Bug fix
- issue #??
- Fix typos found via `typos --hidden --format brief`
=> docs: fix typos

py7zr/helpers.py
=> refactor: use Path instead of PurePath

.github/workflows/release-note.yml
- Other
- Bumped `decathlon/release-notes-generator-action` to `latest`
=> Update `release-note` workflow

py7zr/callbacks.py
Other
None
- Type annotations of a class
=> Add type annotations to ExtractCallback
