Changelog.rst, docs/index.rst, docs/internal_classes.rst, docs/py7zr.rst, py7zr/__init__.py, py7zr/cli.py, py7zr/compression.py, py7zr/py7zr.py, tests/test_basic.py, tests/test_basic_unit.py
Current API includes console interaction. It is not good habits. All of console interaction should be in CLI class and main class should only have a silent API.
Now there are TWO bad APIs and proposals to change
method       |  issue                                                           |  proposal for change
--------------  | --------------------------------------------------------- | --------------------------------------------------
list             |  list shows archive contents with pretty printing.. It accept file descriptor to output. | return list of contents as a FileInfo object. |
archiveinfo |  pretty printing archive information  | return archive information as ArchiveInfo object. |
And then moves pretty printing part into Cli class.
=> Changing SevenZip class exposed API

tests/test_archive.py, tests/test_extract.py
- assert condition as "assert actual == expected" order
- Skip symlink tests on windows.
=> Update test cases for windows

py7zr/compression.py, tests/test_extract.py
COPY method is defined to use make 7-zip archive from 7-zip or zip archive to avoid a duplicated compression.
=> Support decompress of archive with COPY method

py7zr/archiveinfo.py
- Drop last_alternative and loop depends on it.
- Current Folder class assume last_alternative flag,
which does not exist in LZMA SDK 16.00 in p7zip.
=> Fix logics for retrieving coders

py7zr/archiveinfo.py, py7zr/compression.py, py7zr/helpers.py, py7zr/py7zr.py, tests/test_archive.py, tests/test_extract.py, tests/test_unit.py
- use data block sized multiple of 16 bytes for AES decyrption.
thansk for reporting by @andormarkus 
=> Fix AESDecompressor error when encrypted data is not a size with a multiple of 16byte

py7zr/compression.py, py7zr/helpers.py, py7zr/py7zr.py, tests/test_extract.py
- When compression, take link target at a same directory as symlink
exist.
- When decompression, create dummy file first and replace it with
symlink. This helps creating symbolic link not in order of link
path.
- Fix issue #67
=> Fix symlink path

py7zr/compression.py
As #91 comment https://github.com/miurahr/py7zr/pull/91#issuecomment-592874379
multiprocessing is 5 times behind than threading in performance.
This PR change core extraction strategy to Threading.
=> Use threading for extraction

py7zr/compression.py, py7zr/py7zr.py, tests/test_extract.py
- When passing file object, skip threading
- If non-solid archive passed, sequecial call of
extract_single for each folder when decompression.
- Add test a situation call-unlink-extract
=> Skip concurrent extract when passing file object

py7zr/py7zr.py, setup.cfg, tests/test_basic.py
User can instantiate SevenZipFile class like as follows:
```
with SevenZipFile('archvie.7z', 'r') as z:
z.extractall(path=target)
```
- Close #77
=> Introduce context manager for SevenZipFile

py7zr/compression.py, tests/test_extract.py
test case lzmabcj.7z become a status decompressor returns no data.
=> Detect empty decompression from decompressor()

Changelog.rst, py7zr/compression.py, py7zr/py7zr.py
* Refactoring SevenZipFile._write_archive() method to move
core chunk into compression module Worker.archive() method.
=> Refactoring SevenZipFile._write_archive() and Worker.Archive()

py7zr/archiveinfo.py
This fixes exceptions when closing an empty 7z file opened in write mode.
Ex.:
```python
with py7zr.SevenZipFile('/home/andre/test2.7z', 'w') as f:
print('Will not write anything')
```
results in
```
Traceback (most recent call last):
File "/home/andre/Development/andrebrait.github.com/1g1r-romset-generator/test.py", line 7, in <module>
print('Will not write anything')
File "/home/andre/.local/lib/python3.6/site-packages/py7zr/py7zr.py", line 326, in __exit__
self.close()
File "/home/andre/.local/lib/python3.6/site-packages/py7zr/py7zr.py", line 779, in close
self._write_archive()
File "/home/andre/.local/lib/python3.6/site-packages/py7zr/py7zr.py", line 562, in _write_archive
encoded=self.encoded_header_mode)
File "/home/andre/.local/lib/python3.6/site-packages/py7zr/archiveinfo.py", …
```
=> Add default values for reduce operations

py7zr/py7zr.py
=> Release variables when close()

Changelog.rst, docs/py7zr.rst, py7zr/compression.py, py7zr/py7zr.py, tests/test_archive.py
Add support of dereference option(#123)
With dereference= True specified, py7zr will dereference symbolic link to normal files.
=> Support dereference option

py7zr/helpers.py, tests/test_benchmark.py, tests/test_unit.py
Indroduce helper function calculate_key3() which utilize list comprehension expression, bytes generation with join() and reduce a number of calls of update() by concatination of input values in 2048 bytes.
Hash.update(a + b) is equals to Hash.update(a) and Hash.update(b)
=> Introduce helpers.calculate_key3()

py7zr/cli.py, tests/test_basic.py
Primitive implementation of #99
=> Implement volume creation

py7zr/archiveinfo.py, py7zr/compressor.py, py7zr/py7zr.py, tests/test_archive.py
When creating archive, it wrote crc32 digest of packed folders into packinfo.
There is an issue against compatibility with p7zip command for encrypted archive, it disable packinfo.crcs.
=> Calculate crc32 when archive

py7zr/archiveinfo.py
- no-cover for header integrity assertions
- no-cover for external definitions of headers
which is no live example in the wild.
=> Add coverage pragma

docs/archive_format.rst
Add missing bitfield definition
=> docs: Fix spec: packinfo.crcs

py7zr/archiveinfo.py
Support padding with DUMMY ID feature.
=> Add padding with dummy in fileinfo for alignment

py7zr/compressor.py
Fix BCJ filter behavior.
Original BCJ filter in C++ defined uisng uint32_t.
It emulate C++ uint32_t calculation behavior.
Fixed #204, #205
=> Fix bcj filter

py7zr/compressor.py, py7zr/helpers.py, py7zr/properties.py
* Set buffer size to READ_BLOCKSIZE + CBC_BLOCKSIZE * 2
* Change default buffer size for python < v3.7.5 to 32768 bytes.
* Try to fix #201
=> Does not raise BufferOverflow and extend buffer size when necessary

py7zr/__init__.py, py7zr/cli.py, py7zr/compressor.py, py7zr/exceptions.py, tests/test_encryption.py
When extracting encrypted archive without specified
password, it should raise proper exception.
Fixed #215
=> Raise PasswordRequired exception when no password

docs/api.rst, py7zr/compressor.py, py7zr/py7zr.py, tests/test_encryption.py
Trial to implement needs_password() method.
When header is encrypted, SevenZipFile object constructor simply raise PasswordRequired exception as same as before.
=> Support needs_password method

py7zr/compressor.py, tests/test_archive.py
Fix wrong zstandard module name in test_archive.py
Issue https://github.com/miurahr/py7zr/issues/256
=> No longer check compression level for ZstdDecompressor 

docs/api.rst, py7zr/py7zr.py
Introduce methods to set header encoding mode.
=> methods to set header encode mode

py7zr/archiveinfo.py, tests/test_archive.py, tests/test_misc.py
Reproduce the case #266 and fix
=> Fix  KeyError: 'properties' when appending to LZMA2+BCJ archive.

py7zr/archiveinfo.py
Encountered an "Bad7zFile: invalid block data" error when decompressing a valid multi-gigabyte file. Eventually after spending far too much time I traced it down to this line of code!
Theres also a small possibility this might fix #272
=> Fixed bug processing large compressed headers

setup.cfg
pep517 is a command-line tool used by developers interested in building any package, it does not need to be listed as a requirement which `python -m pep517.build` installs into the isolated build environment.
wheel is used optionally by setuptools to run bdist_wheel and is required by the pep517 build backend... but this is only needed if
you're using pyproject.toml's build-system.requires, so this is a duplicate line.
=> setup.cfg: remove build-time dependency on things unrelated to building

py7zr/helpers.py, py7zr/py7zr.py, tests/test_archive.py
Implement a feature request #248 and #290  
- writestr(str_or_bytes, arcname: str) accept str or bytes family data for compression.
when receiving str as argument, it encode it into UTF-8  
- writef(BytesIO_or_binary_fileobject, arcname: str) accept io.BytesIO() memory buffer or file object with open(mode='rb')
=> Introduce writef() and writestr() method

setup.cfg, tests/conftest.py, utils/bench_result.py, utils/github_comment_bench.py
- add py-cpuinfo as test dependency
- Workaround cpuinfo bug
- pass table type as string
=> Refactoring benchmark scripts

utils/bench_result.py
- change label from rate to speed
- add rate of speed compared between filters
- round results
- change ratio to %-tile
=> CI: change benchmark output format

docs/user_guide.rst
=> Doc: fix typo in user_guide.rst

setup.cfg
pyppmd is still in active development and alpha version, so it will be changed drastically.
To protect from defeat, sticking PyPPMd version to 0.12.x
=> stick pyppmd version

setup.cfg
Older version does not accept memoryview, Ref #328
=> Set minimum pycryptodome version

README.rst, docs/user_guide.rst, py7zr/compressor.py, setup.cfg, tests/test_extra_codecs.py
- Cygwin might have old PyCrypto that cause conflict with PyCryptodome(#328)
=> Change depends PyCryptodomex to avoid PyCrypto conflict

README.rst
=> Fix typo in docs about shutil integration

py7zr/py7zr.py
Fixes hanging if an archive contains two files with the same CRC (for some reason). I don't quite get how it fixes that bug, but adding this line seems like it was the intended behaviour nonetheless.
=> Fix infinite loop in SevenZipFile._extract

py7zr/py7zr.py
shutil.make_archive documented as
> Returns the name of the archive file.
and using py7zr currently breaks code relying on returned value.
=> Return created archive name to conform with shutil API

py7zr/py7zr.py
=> Exclude win32 file namespace when cygwin detected

azure-pipelines.yml
- macos 10.14 will be deprecated on azure pipeline in dec. 2021
=> azure: bump macos@10.15

py7zr/py7zr.py
Hi!
I recently started using `py7zr` in [`fs.archive`](https://github.com/althonos/fs.archive) to allow reading 7zip archives using the [PyFilesystem2](https://github.com/PyFilesystem/pyfilesystem2), and it works super well, so congrats!
One of the things I noticed when reading the code was this snippet I removed here, which was erroneously using the `__sizeof__` magic method. Basically, this method can be used by object to provide for their *allocated* size, not for the size of their content as a readable object. For instance, if I open two different files on my computer, `__sizeof__` will return the size of the `io.BufferedReader` object, not the size in bytes of the file. This would be an error here and cause the wrong number of bytes to be compressed.
(also: to check for the allocated …
=> Remove check for `__sizeof__` in `SevenZipFile.writef`

py7zr/callbacks.py, py7zr/py7zr.py, tests/test_basic.py, tests/test_misc.py
- Raising TypeError when passing class not instance
- Improve error messages when wrong callback argument passed
- Reproduce a behavior of  #386
- Put callback basic test in next of error test
=> Improve error messages for callback feature

docs/archive_format.rst
This add an explanation how to store empty file in archive.
=> Docs: spec: add explanation about empty file

docs/api.rst
=> Fix an API doc typo: it should be `BytesIO` instead of `ByteIO`

README.rst
Due to #417 PPMd decompression failed constantly.
This put "(experimental)" for PPMd to notify that it is not stable.
=> Update README: add experimental for PPMd method

pyproject.toml
- Specify license text with its name instead of file key.
- PyPI index try to include all license text from file, that cause overflow the index page.
- Resolve #435
=> Fix pyproject.toml:license

.github/workflows/run-tox-tests.yml, py7zr/compressor.py, py7zr/properties.py, py7zr/py7zr.py, pyproject.toml, setup.cfg, tests/conftest.py, tests/test_misc.py
Reproduce the case and resolve #430
* Add test case to reproduce memory error
* Always pass mem_length for decpmpressor.decompress to limit chunk size
* Detect available memory size to limit decompress chunk size
* Limit maximum chunk size to 512MB.
=> Decompress: limit memory consumptions

README.rst, py7zr/compressor.py, pyproject.toml, setup.cfg, tests/test_extra_codecs.py, tests/test_info.py
``inflate64`` is an alternative library to decompress Deflate64(tm) (Enhanced Deflate) data **without** depending zlib/infback9 patch or lzma-sdk.
It provides wheels for all major platfroms, win, mac and linux, arm64, amd64, i686, and manylinux, musllinux, cpython and pypy.
=> Switch deflate64 decompressor to inflate64

Changelog.rst, MANIFEST.in, py7zr/helpers.py, py7zr/py7zr.py, tests/test_extract.py, tests/test_zipslip.py
- Previous versions do not detect the attack in some case
- fixed it by call resolve()
- resolve() converts "/hoge/fuga/../../../tmp/evil.sh" to be "/tmp/evil.sh" then relative_to() can detect path traversal attack.
- Add path checker in writef() and writestr() methods
- When pass arcname as evil path such as "../../../../tmp/evil.sh" it raises ValueError
- Add test case of bad path detection
- extraction: check symlink and junction is under target folder
- Don't put windows file namespace to output file path
=> Fix sanity check for path traversal attack

py7zr/helpers.py, py7zr/py7zr.py, tests/test_badfiles.py
Introduce helpers.canonical_path()
- Handle '../../' with canonical_path() that handle PurePath object
- Add helpers.is_relative_to(a, b)
- Remove resolve() from path checkers
- Add test cases from aqtinstall project
- Fix is_valid_path check on windows
=> Introduce helpers.canonical_path()

.github/workflows/run-benchmark.yml
- Change to pypy3.7 instead of pypy3
- Bump actions/checkout@v3 and actions/setup-python@v4
=> Actions: fix benchmark script

README.rst, py7zr/cli.py, py7zr/compressor.py, pyproject.toml, tests/test_extra_codecs.py, tests/test_info.py
- inflate64 library raises SIGABORT when compression on pypy
- Skip enhanced compression test on pypy
=> Disable enhanced deflate compression on pypy

docs/user_guide.rst
Typo fixed. 
maanager => manager
=> typo fixed in user_guide.rst

azure-pipelines.yml, pyproject.toml
- test with 3.9, 3.10, 3.11
- small fix of tox.ini to support py311
=> chore(ci): bump host macOS-12

py7zr/properties.py
Fix #521 Avoid AttributeError on OpenBSD
=> fix: use RLIMIT_DATA to get usable memory size

py7zr/archiveinfo.py
`id` is a built-in function so `"Unknown field: %r" % id` will become `'Unknown field: <built-in function id>'`.
=> Fix typo in archiveinfo.py

py7zr/py7zr.py, tests/test_basic.py
https://github.com/miurahr/py7zr/issues/534
=> [Fix#534] IndexError / Worker initialization sets wrong last_file_index 

.github/workflows/run-tox-tests.yml, pyproject.toml
- Bump dependencies
- pycryptodomex@3.16.0
- brotli@1.1.0
- brotlicffi@1.1.0.0
- pyzstd@0.15.9
- pyppmd@1.1.0
- pybcj@1.0.0
- inflate64@1.0.0
- Update Tox envlist
=> chore: Support python 3.12

docs/user_guide.rst, py7zr/compressor.py
- Detect brotli import error and continue
- Only when user try to use brotli when import error, raise exception with message.
- Explain it in documentation
resolve #527
=> fix: Detect brotli import error

py7zr/py7zr.py
- Add reproducible of #546
- Early check of unsupported mode
- Hardening a call of `self._fpclose()` when error handling
- hardening a call of `self.write_flush()`
=> refactor: hardening fp close when error handling

tests/conftest.py
`pyannotate` uses `lib2to3` that will be drop in Python 3.13. So, `pyannotate` will be obsolete in Python 3.13.
`lib2to3` is deprecated in Python 3.11, and it will be removes in Python 3.13. 
See also:
https://docs.python.org/3.12/library/2to3.html#module-lib2to3
=> Drop pyannotate from test code

tests/test_archive.py, tests/test_extract.py
Based on the [deprecated section](https://docs.python.org/3/whatsnew/3.12.html#deprecated) of Python 3.12 documentation about asyncio and datetime modules.
I went for `datetime.datetime.fromtimestamp(..., datetime.timezone.utc)` instead of `datetime.datetime.fromtimestamp(..., datetime.UTC)` as the [latter](https://docs.python.org/3/library/datetime.html#datetime.UTC) is only an alias for the first since 3.11.
[asyncio.get_running_loop](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_running_loop) is only available since 3.7 but if I'm not mistaken this is the minimum required version for this project.
=> fix #540: replace deprecated functions on python 3.12

tests/conftest.py
As of https://github.com/miurahr/py7zr/pull/552 , pyannotate line is now removed.
This patch removes obsolete words in comments.
=> Remove obsolete words in comments

py7zr/py7zr.py
On my system, most of the time was spent on basic python operations like list searches. Changing these to dictionary lookups sped things up significantly when extracting from an archive with ~100K files.
=> Speed up extraction when number of files is very large.

py7zr/callbacks.py, py7zr/cli.py, py7zr/py7zr.py, tests/test_misc.py
- issue #526 
Event "u" (update) is called when file is being extracted more that 1 second or when already extracted.
Function report_update() receives decompressed_bytes count for decompressed part.
Should be useful for progress bar implementation.
```
import py7zr
from tqdm import tqdm
class ExtractProgressBar(py7zr.callbacks.ExtractCallback, tqdm):
def __init__(self, *args, total_bytes, **kwargs):
super().__init__(self, *args, total=total_bytes, **kwargs)
def report_start_preparation(self):
pass
def report_start(self, processing_file_path, processing_bytes):
pass
def report_end(self, processing_file_path, wrote_bytes):
pass
def report_update(self, decompressed_bytes):
self.update(int(decompressed_bytes))
def report_postprocess(self):
pass
def report_warning(self, …
```
=> add report_update() for logging large files extraction

py7zr/py7zr.py, tests/test_archive.py
Ref to issue [#549](https://github.com/miurahr/py7zr/issues/549) and issue [#398](https://github.com/miurahr/py7zr/issues/398). This pull request will fix those issues by treating zero byte stream as a file.
=> Treat zero byte stream as a file.

docs/api.rst, py7zr/py7zr.py, tests/test_basic.py
Add a test case to reproduce issue report #576 
#576 report `arc.read("bar.txt")` returns nothing. It is wrong argument type that should be collection but str.
test on py7zr version v0.20.8 to confirm it is passed,  then merge master and check it become failure but not.
- test on v0.20.8 -- https://github.com/miurahr/py7zr/actions/runs/8133865562?pr=577
- test on master -- https://github.com/miurahr/py7zr/actions/runs/8133905949?pr=577
We should check type of argument before continue to help user to use a method properly. 
- issue #576
- test case that decrypt and read specific target file
- Test with list and set of "bar.txt" entry for  targets argument.
- Test with str in targets argument and it should raise TypeError
=> feat: check `targets` argument type for read and extract method

docs/api.rst, docs/authors.rst, py7zr/py7zr.py
- Feature enhancement --> This one
- None
- Adds the option to set a target directory and extract this directory including all of its subdirectories and the files contained in each subdirectory (including the parent).
=> feat: Add recursive sudirectories and files extraction.

py7zr/py7zr.py
None, it’s a pretty small implementation detail.
- Always call `SevenZipFile.close()` even when there was an exception during `extractall()` in `unpack_7zarchive()`.
=> feat: ensure unpack_7zarchive closes the archive

docs/api.rst
- This PR aims to make the documentation very slightly more consistent by changing one example in the documentation. The current example matches the format in [the shutil doc](https://docs.python.org/3/library/shutil.html#shutil.unpack_archive), whereas the [`pack_7zarchive`](https://py7zr.readthedocs.io/en/latest/api.html#py7zr.pack_7zarchive) example does not.
=> docs: Use same format for `unpack_archive` example as for `make_archive`

docs/user_guide.rst
Made grammatical corrections in the `Programming APIs` --> `Extraction` section of the User Guide.
=> Made grammatical corrections in the `Programming APIs` --> `Extraction` section of the User Guide.

py7zr/archiveinfo.py
Attempting to encode numbers between 0xFFFFFFFFFFFFFF and 0x01FFFFFFFFFFFFFF would result in an error.  Because the byte length is 8, the value of (8 - byte_length - 1) was negative, resulting in an attempt to shift by a negative number of bits which caused an error.
- Bug fix
None that I know of
Changes the threshold for when to use a nine-byte representation of a number.
=> Prevent crash - Change the threshold for a full 9-byte number

py7zr/py7zr.py, tests/test_basic.py
- Bug fix
- Closes https://github.com/miurahr/py7zr/issues/603
- `mode="a"` now works with non-existent files by creating them first. This puts it inline with ZipFile's behavior
=> fix: append mode on non-existent files

docs/api.rst, py7zr/py7zr.py
- issue #553
- Add SevenZipFile.namelist()
- Update api document to add namelist()
=> feat: add SevenZipFile.namelist() method

py7zr/helpers.py, py7zr/py7zr.py, tests/test_getinfo.py
- Closes https://github.com/miurahr/py7zr/issues/608
Implement ZipFile's getinfo
https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.getinfo
=> feat: add `getinfo()`

py7zr/py7zr.py, tests/test_basic.py
Following in the footsteps of https://github.com/miurahr/py7zr/pull/609#issuecomment-2276282122, this PR makes it so `archive.read("some/file/") == archive.read("some/file") is True`. This matches the behavior of [TarFile](https://github.com/python/cpython/blob/c536f59c62eca95f0f4ef3fd688f5c387dd40ae6/Lib/tarfile.py#L1983) and allows for interoperability with ZipFiles
=> fix: handle trailing slash

docs/api.rst
Since `getnames()` and `namelist()` are identical, this PR groups them up in documentation.
This is how it looks now:
=> docs: group getnames and namelist together

.github/workflows/codeql-analysis.yml, .github/workflows/release-note.yml, .github/workflows/run-benchmark.yml, .github/workflows/run-tox-tests.yml, README.rst, docs/contribution.rst, py7zr/archiveinfo.py, py7zr/cli.py, py7zr/compressor.py, py7zr/helpers.py, py7zr/py7zr.py, py7zr/win32compat.py, pyproject.toml
~~Currently nothing, I want the CI to pass with minimal changes before doing anything else~~ CI passed, so time for changes:
=> feat: 3.13 support

.github/workflows/run-tox-tests.yml, docs/advanced.rst, docs/api.rst, docs/authors.rst, docs/index.rst, docs/user_guide.rst, py7zr/__init__.py, py7zr/compressor.py, py7zr/helpers.py, py7zr/io.py, py7zr/py7zr.py, pyproject.toml, tests/test_basic.py, tests/test_encryption.py, tests/test_extract.py, tests/test_misc.py, tests/test_stream.py, tests/test_stream_nwstorage.py, tests/test_unit.py
- refactor: introduce py7zr.io.py
- fix: Drop The read/readall methods
- feat: Extend extract/extactall accept factory callback WriterFactory
- feat: WriterFactory should create Py7zIO object and handle extracted content by user own.
User go wrong with the name "read" and "readall" which they belive it should return stream like zipfile. It is why I remove wrong method names.
Reference #575  and  #579
=> refactor: drop read/readall method, and add feature to stream data into user object

.github/workflows/run-tox-tests.yml
- bundle codacy coverage reporter jar in utils/ folder
=> chore: bundle codacy coverage reporter jar

tests/test_concurrent.py
- Bug fix
- none, I stumbled upon this when packaging py7zr for NixOS in NixOS/nixpkgs#384329
- fixes a test URL that is no longer accessible
=> replace inaccessible mirror (qt.mirrors.tds.net) in test

.github/workflows/run-tox-tests.yml
Added conditions to ensure Java setup and coverage reporting only occur for 'push' events on the 'master' branch. This prevents unnecessary executions on other events or branches, optimizing workflow performance.
- #643 
- if condition for codacy send configuration on CI
-
-
=> chore(ci): Restrict Java setup and coverage report to master pushes

.github/workflows/publish-to-pypi.yml
- Refactor publish workflow into separate distinct "build" and "pypi-publish" jobs to improve security.
- Updated dependencies, permissions, and actions to align with trusted publisher configuration described in https://docs.pypi.org/trusted-publishers/using-a-publisher/
=> chore: publish workflow as trusted publisher

py7zr/py7zr.py, tests/test_basic.py
- Bug fix
- Closes https://github.com/miurahr/py7zr/issues/647
- mode `x` now flushes writes.
- Extended the test
=> fix: `mode="x"` not flushing files in `close()`

.github/workflows/publish-to-pypi.yml
- Other
* Bumped `actions/setup-python` to `v5`
* Bumped Python version to `3.13`
=> Update publish-to-pypi workflow

.github/workflows/run-tox-tests.yml, azure-pipelines.yml
- Other
- `run-tox-tests` workflow
Bumped `libarchive` to latest (`v3.7.9`) for Windows
Bumped `uraimo/run-on-arch-action` to `v3`
- `azure-pipelines` workflow
Added Python 3.12 & Python 3.13
=> Update CI configuration for new Python version and dependencies

py7zr/py7zr.py
- N/A
- Accept any path-like by checking for `os.PathLike` instead.
- Loosen the static types. The method only uses `.read()` and `.seek()` so we should only ask for those.
- Replace `OSError` with `FileNotFoundError` to avoid catching unrelated errors.
N/A
=> fix(is_7zfile): accept any path-like instead of just pathlib.Path

docs/user_guide.rst, py7zr/cli.py, tests/test_cli.py
- issue #669.
- This PR adds a new `--files` CLI argument for `py7zr x` to extract individual files.
n/a
=> feat(cli): add support for extracting specific archive members

py7zr/py7zr.py, tests/test_getinfo.py
- Bug fix
- https://github.com/miurahr/py7zr/issues/675
- `SevenZipFile.getinfo()` now correctly returns `FileInfo` instead of `ArchiveFile`.  
It now looks up the file in `self.list()` (which returns `list[FileInfo]`) instead of `self.files` (`ArchiveFileList`).
While this is technically a backwards-incompatible change, it should be practically compatible because:
- The documentation explicitly states that the return type is `FileInfo`.
- `ArchiveFile` and `FileInfo` have overlapping interfaces.
- `FileInfo` is the return type hint, so type checkers would enforce that only `FileInfo` attributes are accessed.
=> fix: SevenZipFile.getinfo() now returns FileInfo as originally intended

py7zr/py7zr.py
* Feature enhancement
* N/A
This converts `FileInfo` and `ArchiveInfo` into dataclasses. These classes mainly hold data and are part of the public documented API.
All fields are type hinted. Dataclasses automatically provide `__repr__`, `__eq__`, and `__match_args__`, which makes instances easier to inspect and compare. For example, before this change printing a `FileInfo` object showed something like:
```python
<py7zr.py7zr.FileInfo object at 0x00000215C417F250>
```
After converting to a dataclass the output is clear and shows all the field values:
```python
FileInfo(
filename="test1.txt",
compressed=33,
uncompressed=33,
archivable=True,
is_directory=False,
creationtime=datetime.datetime(2006, 3, 15, 21, 43, 48, tzinfo=datetime.timezone.utc),
crc32=140667454,
)
```
This change does not …
=> feat: make FileInfo and ArchiveInfo dataclasses
